######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 9 09:39:16 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4) {
    QT += widgets
    QT += webkitwidgets
} else {
    QT += webkit
}

# Input
HEADERS += baidumap.h
FORMS += baidumap.ui
SOURCES += baidumap.cpp main.cpp
RESOURCES += baidumap.qrc
